title:        Gokulakrishnan
tagline:      'Frontend Developer | Tech Enthusiast'
description:  'Frontend Developer & Tech Enthusiast.'
url:          http://www.gokulkrishh.github.io
version:      1.1.1
author:
  name:       ''
  email:      ''
markdown:     rdiscount
permalink:    pretty
highlighter:  true
paginate:     5
footer-links :
    github : gokulkrishh
    twitter: gokul_i
    facebook: gokulkrishh
    plus: +GokulKalaikoven
    email: krishnangokul9@gmail.com
