title:        Gokulakrishnan
tagline:      'Frontend Developer | Tech Enthusiast'
description:  'Frontend Developer & Tech Enthusiast.'
url:          http://www.gokulkrishh.github.io
version:      1.1.1
author:
  name:       'gokulkrishh'
  email:      'krishnangokul9@gmail'
markdown:     rdiscount
permalink:    pretty
highlighter: pygments
paginate:     3
footer-links :
    github : gokulkrishh
    twitter: gokul_i
    facebook: gokulkrishh
    plus: +GokulKalaikoven
    email: krishnangokul9@gmail.com
