title:        gokulakrishnan
tagline:      'Frontend Developer | Open Source Promoter'
description:  'A passionate frontend developer and an open source promoter.'
url:          http://gokulkrishh.github.io
version:      1.1.1
author:
  name:       ''
  email:      ''
markdown:     rdiscount
permalink:    pretty
highlighter:  true
paginate:     5
