# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hello | Gokulakrishnan
author: Gokulakrishnan Kalaikovan
email: krishnangokul9@gmail.com
description: I ♥ Web / UI Developer / Google Developer Expert at @google
logo: /images/icons/android-chrome-512x512.png
baseurl: ""
url: "https://gokulkrishh.github.io" # the base hostname & protocol for your site
twitter_username: gokul_i
github_username:  gokulkrishh
disqus_shortname:  gokulkrishh

# Build settings
markdown: kramdown
highlighter: rouge

# Server Config options
livereload: true # You no longer need to include --livereload

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-offline

offline: 
  urls_to_cache: 
  
twitter:
  username: gokul_i

social:
  name: Gokulakrishnan Kalaikovan
  links:
    - https://twitter.com/gokul_i
    - https://www.facebook.com/gokulkrishh
    - https://www.linkedin.com/in/gokulkrishh
    - https://plus.google.com/+GokulKalaikovan
    - https://plus.google.com/+GokulKalaikoven

facebook:
  app_id: 1845428102398128

google_site_verification: tWzbp4_ZxYPdhc-YtdGItiKH3-Ui3qptrbQ53xXCyUQ
