# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hello | Gokulakrishnan
email: krishnangokul9@gmail.com
description: 
baseurl: ""
url: "https://gokulkrishh.github.io" # the base hostname & protocol for your site
twitter_username: gokul_i
github_username:  gokulkrishh

# Build settings
markdown: kramdown
